### ISSUE TITLE
Where is the requirements.txt?

### ISSUE THREAD

**Issue by yashb042** [HugoM25/Character_Versus_Video_Generator#1]

**Comment by HugoM25** [comment]
I added the missing requirements.txt file. [here](https://github.com/HugoM25/Character_Versus_Video_Generator/blob/master/requirements.txt)

**Comment by yashb042** [comment]
If possible could you please add the sample videos for one time setup?
Then we can get clear idea on the directory structure.
You just have to add the videos in the directory like you mentioned. 
TIA
